name: google_oauth2
version: 1.0.1
description: A Dart library for generating OAuth 2.0 access tokens for Google
  APIs using JSON service account credentials.
repository: https://github.com/Sevastyan/google_oauth2
issue_tracker: https://github.com/Sevastyan/google_oauth2/issues
topics:
  - oauth
  - google-apis
false_secrets:
  - /test/data/service_account_example.json

environment:
  sdk: ^3.2.3

dependencies:
  http: ^1.2.0
  pointycastle: ^3.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.25.4
